name = "errooe-api"
compatibility_date = "2023-12-01"

# Dev environment
[env.dev]
vars = { ENVIRONMENT = "development" }

[[env.dev.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 50, period = 10 }

# Production environment
[env.production]
name = "errooe-api"
vars = { ENVIRONMENT = "production" }

[[env.production.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 25, period = 10 }